// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: package.proto

#ifndef PROTOBUF_package_2eproto__INCLUDED
#define PROTOBUF_package_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace pb {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_package_2eproto();
void protobuf_AssignDesc_package_2eproto();
void protobuf_ShutdownFile_package_2eproto();

class c2s_login;
class s2c_login;
class c2s_create_room;
class s2c_create_room;
class c2s_quit_room;
class s2c_quit_room;
class c2s_enter_room;
class s2c_enter_room;

// ===================================================================

class c2s_login : public ::google::protobuf::Message {
 public:
  c2s_login();
  virtual ~c2s_login();

  c2s_login(const c2s_login& from);

  inline c2s_login& operator=(const c2s_login& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const c2s_login& default_instance();

  void Swap(c2s_login* other);

  // implements Message ----------------------------------------------

  c2s_login* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const c2s_login& from);
  void MergeFrom(const c2s_login& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 uid = 1;
  inline bool has_uid() const;
  inline void clear_uid();
  static const int kUidFieldNumber = 1;
  inline ::google::protobuf::uint32 uid() const;
  inline void set_uid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:pb.c2s_login)
 private:
  inline void set_has_uid();
  inline void clear_has_uid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 uid_;
  friend void  protobuf_AddDesc_package_2eproto();
  friend void protobuf_AssignDesc_package_2eproto();
  friend void protobuf_ShutdownFile_package_2eproto();

  void InitAsDefaultInstance();
  static c2s_login* default_instance_;
};
// -------------------------------------------------------------------

class s2c_login : public ::google::protobuf::Message {
 public:
  s2c_login();
  virtual ~s2c_login();

  s2c_login(const s2c_login& from);

  inline s2c_login& operator=(const s2c_login& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const s2c_login& default_instance();

  void Swap(s2c_login* other);

  // implements Message ----------------------------------------------

  s2c_login* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const s2c_login& from);
  void MergeFrom(const s2c_login& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:pb.s2c_login)
 private:
  inline void set_has_result();
  inline void clear_has_result();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 result_;
  friend void  protobuf_AddDesc_package_2eproto();
  friend void protobuf_AssignDesc_package_2eproto();
  friend void protobuf_ShutdownFile_package_2eproto();

  void InitAsDefaultInstance();
  static s2c_login* default_instance_;
};
// -------------------------------------------------------------------

class c2s_create_room : public ::google::protobuf::Message {
 public:
  c2s_create_room();
  virtual ~c2s_create_room();

  c2s_create_room(const c2s_create_room& from);

  inline c2s_create_room& operator=(const c2s_create_room& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const c2s_create_room& default_instance();

  void Swap(c2s_create_room* other);

  // implements Message ----------------------------------------------

  c2s_create_room* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const c2s_create_room& from);
  void MergeFrom(const c2s_create_room& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::uint32 type() const;
  inline void set_type(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:pb.c2s_create_room)
 private:
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 type_;
  friend void  protobuf_AddDesc_package_2eproto();
  friend void protobuf_AssignDesc_package_2eproto();
  friend void protobuf_ShutdownFile_package_2eproto();

  void InitAsDefaultInstance();
  static c2s_create_room* default_instance_;
};
// -------------------------------------------------------------------

class s2c_create_room : public ::google::protobuf::Message {
 public:
  s2c_create_room();
  virtual ~s2c_create_room();

  s2c_create_room(const s2c_create_room& from);

  inline s2c_create_room& operator=(const s2c_create_room& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const s2c_create_room& default_instance();

  void Swap(s2c_create_room* other);

  // implements Message ----------------------------------------------

  s2c_create_room* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const s2c_create_room& from);
  void MergeFrom(const s2c_create_room& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);

  // required uint32 room_num = 2;
  inline bool has_room_num() const;
  inline void clear_room_num();
  static const int kRoomNumFieldNumber = 2;
  inline ::google::protobuf::uint32 room_num() const;
  inline void set_room_num(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:pb.s2c_create_room)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_room_num();
  inline void clear_has_room_num();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 result_;
  ::google::protobuf::uint32 room_num_;
  friend void  protobuf_AddDesc_package_2eproto();
  friend void protobuf_AssignDesc_package_2eproto();
  friend void protobuf_ShutdownFile_package_2eproto();

  void InitAsDefaultInstance();
  static s2c_create_room* default_instance_;
};
// -------------------------------------------------------------------

class c2s_quit_room : public ::google::protobuf::Message {
 public:
  c2s_quit_room();
  virtual ~c2s_quit_room();

  c2s_quit_room(const c2s_quit_room& from);

  inline c2s_quit_room& operator=(const c2s_quit_room& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const c2s_quit_room& default_instance();

  void Swap(c2s_quit_room* other);

  // implements Message ----------------------------------------------

  c2s_quit_room* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const c2s_quit_room& from);
  void MergeFrom(const c2s_quit_room& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 room_num = 1;
  inline bool has_room_num() const;
  inline void clear_room_num();
  static const int kRoomNumFieldNumber = 1;
  inline ::google::protobuf::uint32 room_num() const;
  inline void set_room_num(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:pb.c2s_quit_room)
 private:
  inline void set_has_room_num();
  inline void clear_has_room_num();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 room_num_;
  friend void  protobuf_AddDesc_package_2eproto();
  friend void protobuf_AssignDesc_package_2eproto();
  friend void protobuf_ShutdownFile_package_2eproto();

  void InitAsDefaultInstance();
  static c2s_quit_room* default_instance_;
};
// -------------------------------------------------------------------

class s2c_quit_room : public ::google::protobuf::Message {
 public:
  s2c_quit_room();
  virtual ~s2c_quit_room();

  s2c_quit_room(const s2c_quit_room& from);

  inline s2c_quit_room& operator=(const s2c_quit_room& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const s2c_quit_room& default_instance();

  void Swap(s2c_quit_room* other);

  // implements Message ----------------------------------------------

  s2c_quit_room* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const s2c_quit_room& from);
  void MergeFrom(const s2c_quit_room& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:pb.s2c_quit_room)
 private:
  inline void set_has_result();
  inline void clear_has_result();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 result_;
  friend void  protobuf_AddDesc_package_2eproto();
  friend void protobuf_AssignDesc_package_2eproto();
  friend void protobuf_ShutdownFile_package_2eproto();

  void InitAsDefaultInstance();
  static s2c_quit_room* default_instance_;
};
// -------------------------------------------------------------------

class c2s_enter_room : public ::google::protobuf::Message {
 public:
  c2s_enter_room();
  virtual ~c2s_enter_room();

  c2s_enter_room(const c2s_enter_room& from);

  inline c2s_enter_room& operator=(const c2s_enter_room& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const c2s_enter_room& default_instance();

  void Swap(c2s_enter_room* other);

  // implements Message ----------------------------------------------

  c2s_enter_room* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const c2s_enter_room& from);
  void MergeFrom(const c2s_enter_room& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 room_num = 1;
  inline bool has_room_num() const;
  inline void clear_room_num();
  static const int kRoomNumFieldNumber = 1;
  inline ::google::protobuf::uint32 room_num() const;
  inline void set_room_num(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:pb.c2s_enter_room)
 private:
  inline void set_has_room_num();
  inline void clear_has_room_num();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 room_num_;
  friend void  protobuf_AddDesc_package_2eproto();
  friend void protobuf_AssignDesc_package_2eproto();
  friend void protobuf_ShutdownFile_package_2eproto();

  void InitAsDefaultInstance();
  static c2s_enter_room* default_instance_;
};
// -------------------------------------------------------------------

class s2c_enter_room : public ::google::protobuf::Message {
 public:
  s2c_enter_room();
  virtual ~s2c_enter_room();

  s2c_enter_room(const s2c_enter_room& from);

  inline s2c_enter_room& operator=(const s2c_enter_room& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const s2c_enter_room& default_instance();

  void Swap(s2c_enter_room* other);

  // implements Message ----------------------------------------------

  s2c_enter_room* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const s2c_enter_room& from);
  void MergeFrom(const s2c_enter_room& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:pb.s2c_enter_room)
 private:
  inline void set_has_result();
  inline void clear_has_result();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 result_;
  friend void  protobuf_AddDesc_package_2eproto();
  friend void protobuf_AssignDesc_package_2eproto();
  friend void protobuf_ShutdownFile_package_2eproto();

  void InitAsDefaultInstance();
  static s2c_enter_room* default_instance_;
};
// ===================================================================


// ===================================================================

// c2s_login

// required uint32 uid = 1;
inline bool c2s_login::has_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void c2s_login::set_has_uid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void c2s_login::clear_has_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void c2s_login::clear_uid() {
  uid_ = 0u;
  clear_has_uid();
}
inline ::google::protobuf::uint32 c2s_login::uid() const {
  // @@protoc_insertion_point(field_get:pb.c2s_login.uid)
  return uid_;
}
inline void c2s_login::set_uid(::google::protobuf::uint32 value) {
  set_has_uid();
  uid_ = value;
  // @@protoc_insertion_point(field_set:pb.c2s_login.uid)
}

// -------------------------------------------------------------------

// s2c_login

// required int32 result = 1;
inline bool s2c_login::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void s2c_login::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void s2c_login::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void s2c_login::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 s2c_login::result() const {
  // @@protoc_insertion_point(field_get:pb.s2c_login.result)
  return result_;
}
inline void s2c_login::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:pb.s2c_login.result)
}

// -------------------------------------------------------------------

// c2s_create_room

// required uint32 type = 1;
inline bool c2s_create_room::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void c2s_create_room::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void c2s_create_room::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void c2s_create_room::clear_type() {
  type_ = 0u;
  clear_has_type();
}
inline ::google::protobuf::uint32 c2s_create_room::type() const {
  // @@protoc_insertion_point(field_get:pb.c2s_create_room.type)
  return type_;
}
inline void c2s_create_room::set_type(::google::protobuf::uint32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:pb.c2s_create_room.type)
}

// -------------------------------------------------------------------

// s2c_create_room

// required int32 result = 1;
inline bool s2c_create_room::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void s2c_create_room::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void s2c_create_room::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void s2c_create_room::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 s2c_create_room::result() const {
  // @@protoc_insertion_point(field_get:pb.s2c_create_room.result)
  return result_;
}
inline void s2c_create_room::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:pb.s2c_create_room.result)
}

// required uint32 room_num = 2;
inline bool s2c_create_room::has_room_num() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void s2c_create_room::set_has_room_num() {
  _has_bits_[0] |= 0x00000002u;
}
inline void s2c_create_room::clear_has_room_num() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void s2c_create_room::clear_room_num() {
  room_num_ = 0u;
  clear_has_room_num();
}
inline ::google::protobuf::uint32 s2c_create_room::room_num() const {
  // @@protoc_insertion_point(field_get:pb.s2c_create_room.room_num)
  return room_num_;
}
inline void s2c_create_room::set_room_num(::google::protobuf::uint32 value) {
  set_has_room_num();
  room_num_ = value;
  // @@protoc_insertion_point(field_set:pb.s2c_create_room.room_num)
}

// -------------------------------------------------------------------

// c2s_quit_room

// required uint32 room_num = 1;
inline bool c2s_quit_room::has_room_num() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void c2s_quit_room::set_has_room_num() {
  _has_bits_[0] |= 0x00000001u;
}
inline void c2s_quit_room::clear_has_room_num() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void c2s_quit_room::clear_room_num() {
  room_num_ = 0u;
  clear_has_room_num();
}
inline ::google::protobuf::uint32 c2s_quit_room::room_num() const {
  // @@protoc_insertion_point(field_get:pb.c2s_quit_room.room_num)
  return room_num_;
}
inline void c2s_quit_room::set_room_num(::google::protobuf::uint32 value) {
  set_has_room_num();
  room_num_ = value;
  // @@protoc_insertion_point(field_set:pb.c2s_quit_room.room_num)
}

// -------------------------------------------------------------------

// s2c_quit_room

// required int32 result = 1;
inline bool s2c_quit_room::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void s2c_quit_room::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void s2c_quit_room::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void s2c_quit_room::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 s2c_quit_room::result() const {
  // @@protoc_insertion_point(field_get:pb.s2c_quit_room.result)
  return result_;
}
inline void s2c_quit_room::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:pb.s2c_quit_room.result)
}

// -------------------------------------------------------------------

// c2s_enter_room

// required uint32 room_num = 1;
inline bool c2s_enter_room::has_room_num() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void c2s_enter_room::set_has_room_num() {
  _has_bits_[0] |= 0x00000001u;
}
inline void c2s_enter_room::clear_has_room_num() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void c2s_enter_room::clear_room_num() {
  room_num_ = 0u;
  clear_has_room_num();
}
inline ::google::protobuf::uint32 c2s_enter_room::room_num() const {
  // @@protoc_insertion_point(field_get:pb.c2s_enter_room.room_num)
  return room_num_;
}
inline void c2s_enter_room::set_room_num(::google::protobuf::uint32 value) {
  set_has_room_num();
  room_num_ = value;
  // @@protoc_insertion_point(field_set:pb.c2s_enter_room.room_num)
}

// -------------------------------------------------------------------

// s2c_enter_room

// required int32 result = 1;
inline bool s2c_enter_room::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void s2c_enter_room::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void s2c_enter_room::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void s2c_enter_room::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 s2c_enter_room::result() const {
  // @@protoc_insertion_point(field_get:pb.s2c_enter_room.result)
  return result_;
}
inline void s2c_enter_room::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:pb.s2c_enter_room.result)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_package_2eproto__INCLUDED
